name: CI/CD Pipeline with Docker

on:
  push:
    branches: [ main, develop, feature-digital ]
  pull_request:
    branches: [ feature-digital ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make
    
    - name: Verify build tools
      run: |
        which gcc
        which make
        gcc --version
        make --version
    
    - name: Compile the project
      run: make
    
    - name: Run the program
      run: make run
    
    - name: Check for memory leaks (optional)
      run: |
        sudo apt-get install -y valgrind
        valgrind --leak-check=full --error-exitcode=1 ./main

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t ci-cd-test:latest .
    
    - name: Test Docker image
      run: |
        docker run --rm ci-cd-test:latest
    
    - name: Build multi-stage Docker image
      run: |
        docker build -f Dockerfile.multistage -t ci-cd-test:multistage .
    
    - name: Test multi-stage Docker image
      run: |
        docker run --rm ci-cd-test:multistage
    
    - name: Show Docker images
      run: |
        docker images | grep ci-cd-test

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make
        update: true
    
    - name: Compile the project (Windows)
      shell: msys2 {0}
      run: make
    
    - name: Run the program (Windows)
      shell: msys2 {0}
      run: make run

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        brew install gcc make
    
    - name: Compile the project (macOS)
      run: make
    
    - name: Run the program (macOS)
      run: make run
